version: '3.8'
services:
  vprodb:
    container_name: vprodb
    image: raghib1992/vprofiledb
    build:
      context: ./Docker-files/db
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"
  
  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
    container_name: vproapp
    image: raghib1992/vprofileapp
    build:
      context: ./Docker-files/app
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps

  vproweb:
    container_name: vproweb
    image: raghib1992/vprofileweb
    build:
      context: ./Docker-files/web
    ports:
      - "80:80"

volumes:
- vproappdata: {}
- vprodbdata: {}
